name: Dependabot Dockerfile CI

on:
  pull_request:
    branches:
      - main
      
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:

  dependabot-test-build:
  
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      actions: read

    if: github.actor == 'dependabot[bot]'   # Only run on Dependabot PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}                                                                     
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/bake-action
      - name: Build Docker image
        id: build-and-push
        uses: docker/bake-action@v5 #v5.3.0
        with:
          push: false
          load: true
          targets: |
            default
          files: |
            ./docker-bake.hcl
            ./docker-bake-leaf-version-override.json
          set: |
            *.tags=localbuild/testimage:latest    
