name: Build and publish

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push:
    branches:
      - '**' # all branches; with or without '/'
      - '!main' # exclude main
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  # pull_request:
  #   branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      attestations: write

    steps:

      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v6

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      #- name: Install cosign
      #  if: github.event_name != 'pull_request'
      #  uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
      #  with:
      #    cosign-release: 'v2.1.1'

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@65d18f8f8a05aab1b2d761032bec9cd5578caadb # v3.3.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,enable=true,pattern={{version}}
            type=semver,enable=true,pattern={{major}}.{{minor}}
            type=semver,enable=true,pattern={{major}}
            type=ref,enable=true,event=branch
            type=ref,enable=false,event=tag
            type=ref,enable=false,event=pr

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/bake-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/bake-action@v5 #v5.3.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          load: true
          #provenance: true
          #sbom: true
          targets: |
            default
          files: |
            ./docker-bake.hcl
            ./docker-bake-leaf-version-override.json
            ${{ steps.meta.outputs.bake-file }}
          #cache-from: type=gha
          #cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      #- name: Sign the published Docker image
      #  if: ${{ github.event_name != 'pull_request' }}
      #  env:
      #    # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      #    TAGS: ${{ steps.meta.outputs.tags }}
      #    DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #  # This step uses the identity token to provision an ephemeral certificate
      #  # against the sigstore community Fulcio instance.
      #  run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      # https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
      #- name: Generate artifact attestation
        #uses: actions/attest-build-provenance@v1
        #with:
          #subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          #subject-digest: ${{ steps.build-and-push.outputs.digest }}
          #push-to-registry: true
